// flask-reactjs/src/components/Navbar/index.js
import React, { Component } from 'react'
import { Link, withRouter } from 'react-router-dom'
import logo from '../../assets/logo.jpeg'
import store from '../../utils/store'
import styles from './index.module.css'

class Navbar extends Component {
  state = {
    sharedState: store.state
  }

  handlerLogout() {
    const { history } = this.props
    store.logoutAction()
    history.push('/login')
  }

  renderIsLoginButton() {
    // 登陆后显示退出按钮，未登录显示登陆
    if (!store.state.is_authenticated) {
      return <li className="nav-item">
        <Link className="nav-link" to="/login">Login</Link>
      </li>
    } else return <li className="nav-item">
      <div className="nav-link" onClick={() => this.handlerLogout()}>Loginout</div>
    </li>
  }

  render() {
    return (
      <nav className={"navbar navbar-expand-lg navbar-light bg-light "+ styles.navBottom}>
        <div className="container">
          <Link className="navbar-brand" to="/">
            <img src={logo} width="30px" height="30px" className="d-inline-block align-top" alt="" />
          </Link>
          <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"></span>
          </button>

          <div className="collapse navbar-collapse" id="navbarSupportedContent">
            <ul className="navbar-nav mr-auto mt-2 mt-lg-0">
              <li className="nav-item active">
                <Link className="nav-link" to="/">Home <span className="sr-only">(current)</span></Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link disabled" to="/#">Explore</Link>
              </li>
            </ul>
            <form className="form-inline navbar-left mr-auto">
              <input className="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" />
              <button className="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            <ul className="nav navbar-nav navbar-right">
              <li className="nav-item">
                <Link className="nav-link disabled" to="/#">Message</Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" to={`/profile/${this.state.sharedState.user_id}/Overview`}>Profile</Link>
              </li>
              {
                this.renderIsLoginButton()
              }
            </ul>
          </div>
        </div>
      </nav>
    )
  }
}

export default withRouter(Navbar)

// front-end/src/components/Base/Navbar.vue
<template>
  <nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom: 20px;">
    <div class="container">
      <router-link to="/" class="navbar-brand">
        <img src="../../assets/logo.png" width="30" height="30" class="d-inline-block align-top" alt>
          MyBlog
      </router-link>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <router-link to="/" class="nav-link">
              Home
              <span class="sr-only">(current)</span>
            </router-link>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Explore</a>
          </li>
          <li class="nav-item">
            <router-link to="/Demo" class="nav-link">
              Demo
              <span class="sr-only">(current)</span>
            </router-link>
          </li>
        </ul>

        <form v-if="sharedState.is_authenticated" class="form-inline navbar-left mr-auto">
          <input class="form-control mr-sm-2" type="search" placeholder="Search">
          <!-- 暂时先禁止提交，后续实现搜索再改回 type="submit" -->
          <button class="btn btn-outline-success my-2 my-sm-0" type="button">Search</button>
        </form>

        <ul v-if="sharedState.is_authenticated" class="nav navbar-nav navbar-right">
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdown"
              role="button"
              data-toggle="dropdown"
              aria-haspopup="true"
              aria-expanded="false"
            >
              <img v-bind:src="sharedState.user_avatar">
              {{ sharedState.user_name }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <router-link
                v-bind:to="{ path: `/user/${sharedState.user_id}` }"
                class="dropdown-item"
              >Your profile</router-link>
              <router-link v-bind:to="{ name: 'SettingProfile' }" class="dropdown-item">Settings</router-link>
              <div class="dropdown-divider"></div>
              <a v-on:click="handlerLogout" class="dropdown-item" href="#">Sign out</a>
            </div>
          </li>
        </ul>
        <ul v-else class="nav navbar-nav navbar-right">
          <li class="nav-item">
            <router-link to="/login" class="nav-link">Login</router-link>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>

<script>
import store from '../../store.js'

export default {
  name: 'Navbar', // this is the name of the component
  data() {
    return {
      sharedState: store.state
    }
  },
  methods: {
    handlerLogout(e) {
      store.logoutAction()
      this.$toasted.show('You have been logged out.', { icon: 'fingerprint' })
      this.$router.push('/login')
    }
  }
}
</script>
