// flask-reactjs/src/pages/Register/index.js
import React, { useState } from 'react'
import { API } from '../../utils/api'
import store from '../../utils/store'


const Register = ({history}) => {

  const [registerForm, setRegisterForm] = useState({
    username: '',
    email: '',
    password: '',
    usernameError: null,
    emailError: null,
    passwordError: null
  })

  const setInput = ({ target }) => {
    const value = target.value
    const name = target.id
    setRegisterForm((currentRegisterForm) => {
      return { ...currentRegisterForm, [name]: value, [name + 'Error']: null }
    })
  }

  const validEmail = email => {
    var re = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    return re.test(email)
  }

  const onSubmit = async (e) => {
    e.preventDefault()
    const { username, email, password } = registerForm
    const formData = {}

    let error = 0
    // 验证邮箱名
    if (!username) {
      formData.usernameError = 'Username required'
      error++
    } else {
      formData.usernameError = null
    }
    // 验证邮箱
    if (!email) {
      formData.emailError = 'Email required'
      error++
    } else if (!validEmail(email)) {
      formData.emailError = 'Valid email required'
      error++
    } else {
      formData.emailError = null
    }
    // 验证密码
    if (!password) {
      formData.passwordError = 'Password required'
      error++
    } else {
      formData.passwordError = null
    }
    if (error > 0) {
      setRegisterForm({...registerForm, ...formData})
      return false
    }

    const payload = {
      username: registerForm.username,
      email: registerForm.email,
      password: registerForm.password
    }

    const res = await API.post('/users', payload)

    if (res.status === 201) {
      store.setNewAction()
      history.push('/login')
    } else {
      const { message } = res.data
      const errorData = {}
      for (var field in message) {
        if (field === 'username') {
          errorData.usernameError = message.username
        } else if (field === 'email') {
          errorData.emailError = message.email
        } else {
          errorData.passwordError = message.password
        }
      }
      setRegisterForm((currentData) => {
        return {...currentData, ...errorData}
      })
    }
  }

  return (
    <div className="container">
      <h1>Register</h1>
      <div className="row">
        <div className="col-md-4">
          <form onSubmit={onSubmit}>
            <div className="form-group">
              <label htmlFor="username">Username</label>
              <input onChange={setInput} value={registerForm.username} type="text" className={['form-control', registerForm.usernameError ? 'is-invalid' : ''].join(" ")} id="username" placeholder="" />
              <div className="invalid-feedback">{registerForm.usernameError}</div>
            </div>
            <div className="form-group">
              <label htmlFor="email">Email address</label>
              <input type="email" onChange={setInput} value={registerForm.email} className={['form-control', registerForm.emailError ? 'is-invalid' : ''].join(" ")} id="email" aria-describedby="emailHelp" placeholder="" />
              <small id="emailHelp" className="form-text text-muted">We'll never share your email with anyone else.</small>
              <div className="invalid-feedback">{registerForm.emailError}</div>
            </div>
            <div className="form-group">
              <label htmlFor="password">Password</label>
              <input type="password" onChange={setInput} value={registerForm.password} className={['form-control', registerForm.passwordError ? 'is-invalid' : ''].join(" ")} id="password" placeholder="" />
              <div className="invalid-feedback">{registerForm.passwordError}</div>
            </div>
            <button type="submit" className="btn btn-primary">Register</button>
          </form>
        </div>
      </div>
    </div>
  )
}

export default Register

// front-end/src/components/Register.vue
<template>
  <div class="container">
    <h1>Register</h1>
    <div class="row">
      <div class="col-md-4">
        <form @submit.prevent="onSubmit" ref="register">
          <div class="form-group">
            <label for="username">Username</label>
            <input
              type="text"
              v-model="registerForm.username"
              class="form-control"
              v-bind:class="{'is-invalid': registerForm.usernameError}"
              id="username"
              placeholder
            >
            <div
              v-show="registerForm.usernameError"
              class="invalid-feedback"
            >{{ registerForm.usernameError }}</div>
          </div>
          <div class="form-group">
            <label for="email">Email address</label>
            <input
              type="email"
              v-model="registerForm.email"
              class="form-control"
              v-bind:class="{'is-invalid': registerForm.emailError}"
              id="email"
              aria-describedby="emailHelp"
              placeholder
            >
            <small
              v-if="!registerForm.emailError"
              id="emailHelp"
              class="form-text text-muted"
            >We'll never share your email with anyone else.</small>
            <div
              v-show="registerForm.emailError"
              class="invalid-feedback"
            >{{ registerForm.emailError }}</div>
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input
              type="password"
              v-model="registerForm.password"
              class="form-control"
              v-bind:class="{'is-invalid': registerForm.passwordError}"
              id="password"
              placeholder
            >
            <div
              v-show="registerForm.passwordError"
              class="invalid-feedback"
            >{{ registerForm.passwordError }}</div>
          </div>
          <button type="submit" class="btn btn-primary">Register</button>
        </form>
      </div>
    </div>
  </div>
</template>

<script>
import axios from 'axios'
import store from '../store.js'

export default {
  name: 'Register', // this is the name of the component
  data () {
    return {
      registerForm: {
        username: '',
        email: '',
        password: '',
        submitted: false, // 是否点击了 submit 按钮
        errors: 0, // 表单是否在前端验证通过，0 表示没有错误，验证通过
        usernameError: null,
        emailError: null,
        passwordError: null
      }
    }
  },
  methods: {
    onSubmit (e) {
      console.log(e)
      console.log(this.$ref.register)
      this.registerForm.submitted = true // 先更新状态
      this.registerForm.errors = 0

      if (!this.registerForm.username) {
        this.registerForm.errors++
        this.registerForm.usernameError = 'Username required.'
      } else {
        this.registerForm.usernameError = null
      }

      if (!this.registerForm.email) {
        this.registerForm.errors++
        this.registerForm.emailError = 'Email required.'
      } else if (!this.validEmail(this.registerForm.email)) {
        this.registerForm.errors++
        this.registerForm.emailError = 'Valid email required.'
      } else {
        this.registerForm.emailError = null
      }

      if (!this.registerForm.password) {
        this.registerForm.errors++
        this.registerForm.passwordError = 'Password required.'
      } else {
        this.registerForm.passwordError = null
      }

      if (this.registerForm.errors > 0) {
        // 表单验证没通过时，不继续往下执行，即不会通过 axios 调用后端API
        return false
      }

      const path = '/users'
      const payload = {
        username: this.registerForm.username,
        email: this.registerForm.email,
        password: this.registerForm.password
      }
      axios
        .post(path, payload)
        .then(response => {
          // handle success
          store.setNewAction()
          this.$router.push('/login')
        })
        .catch(error => {
          // handle error
          for (var field in error.response.data.message) {
            if (field === 'username') {
              this.registerForm.usernameError =
                error.response.data.message.username
            } else if (field === 'email') {
              this.registerForm.emailError = error.response.data.message.email
            } else if (field === 'password') {
              this.registerForm.passwordError =
                error.response.data.message.password
            }
          }
        })
    },
    validEmail: function (email) {
      var re = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
      return re.test(email)
    }
  }
}
</script>
