// front-end/src/components/Login.vue
<template>
  <div class="container">
    <h1>Sign In</h1>
    <div class="row">
      <div class="col-md-4">
        <form @submit.prevent="onSubmit">
          <div class="form-group">
            <label for="username">Username</label>
            <input
              type="text"
              v-model="loginForm.username"
              class="form-control"
              v-bind:class="{'is-invalid': loginForm.usernameError}"
              id="username"
              placeholder
            >
            <div
              v-show="loginForm.usernameError"
              class="invalid-feedback"
            >{{ loginForm.usernameError }}</div>
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input
              type="password"
              v-model="loginForm.password"
              class="form-control"
              v-bind:class="{'is-invalid': loginForm.passwordError}"
              id="password"
              placeholder
            >
            <div
              v-show="loginForm.passwordError"
              class="invalid-feedback"
            >{{ loginForm.passwordError }}</div>
          </div>
          <button type="submit" class="btn btn-primary">Sign In</button>
        </form>
      </div>
    </div>
    <br>
    <p>
      New User?
      <router-link to="/register">Click to Register!</router-link>
    </p>
    <p>
      Forgot Your Password?
      <a href="#">Click to Reset It</a>
    </p>
  </div>
</template>

<script>
import store from '../store.js'
export default {
  name: 'Login', // this is the name of the component
  data () {
    return {
      sharedState: store.state,
      loginForm: {
        username: '',
        password: '',
        submitted: false, // 是否点击了 submit 按钮
        errors: 0, // 表单是否在前端验证通过，0 表示没有错误，验证通过
        usernameError: null,
        passwordError: null
      }
    }
  },
  methods: {
    onSubmit (e) {
      this.loginForm.submitted = true // 先更新状态
      this.loginForm.errors = 0
      if (!this.loginForm.username) {
        this.loginForm.errors++
        this.loginForm.usernameError = 'Username required.'
      } else {
        this.loginForm.usernameError = null
      }
      if (!this.loginForm.password) {
        this.loginForm.errors++
        this.loginForm.passwordError = 'Password required.'
      } else {
        this.loginForm.passwordError = null
      }
      if (this.loginForm.errors > 0) {
        // 表单验证没通过时，不继续往下执行，即不会通过 axios 调用后端API
        return false
      }
      const path = '/tokens'
      // axios 实现Basic Auth需要在config中设置 auth 这个属性即可
      this.$axios({
        methods: 'GET',
        url: path,
        auth: {
          username: this.loginForm.username,
          password: this.loginForm.password
        }
      })
        .then(response => {
          // handle success
          window.localStorage.setItem('madblog-token', response.data.token)
          store.loginAction()
          const name = JSON.parse(atob(response.data.token.split('.')[1])).name
          this.$toasted.success(`Welcome ${name}!`, { icon: 'fingerprint' })
          if (typeof this.$route.query.redirect === 'undefined') {
            this.$router.push('/')
          } else {
            this.$router.push(this.$route.query.redirect)
          }
        })
        .catch(error => {
          // handle error
          if (error.response.status === 401) {
            this.loginForm.usernameError = 'Invalid username or password.'
            this.loginForm.passwordError = 'Invalid username or password.'
          } else {
            console.log(error.response)
          }
        })
    }
  }
}
</script>

// flask-reactjs/src/pages/Login/index.js
import React from 'react'
import { Link } from 'react-router-dom'
import { API } from '../../utils/api'
import { setToken } from '../../utils/auth'
import { Field, Form, ErrorMessage, withFormik } from 'formik';
import store from '../../utils/store'
import * as Yup from 'yup';
import { toast } from 'react-toastify'


let Login = ({errors, touched, isSubmitting}) => {
  return (
      <div className="container">
        <h1>Sign In</h1>
        <div className="row">
          <div className="col-md-4">
            <Form>
              <div className="form-group">
                <label htmlFor="username">Username</label>
                <Field type="text"
                  className={["form-control", errors.username && touched.username && "is-invalid"].join(" ")}
                  name="username" placeholder=""/>
                {/* <div className="invalid-feedback">{loginForm.usernameError ? loginForm.usernameError : null}</div> */}
                <ErrorMessage name="username" className="invalid-feedback" component="div"/>
              </div>
              <div className="form-group">
                <label htmlFor="password">Password</label>
                <Field type="password"
                  className={["form-control", errors.password && touched.password && "is-invalid"].join(" ")}
                  name="password" placeholder=""/>
                <ErrorMessage name="password" className="invalid-feedback" component="div"/>
              </div>
              <button type="submit" className="btn btn-primary" disabled={isSubmitting}>Sign In</button>
            </Form>
          </div>
        </div>
        <br/>
        <p>New User? <Link to="register">Click to Register</Link></p>
        <p>
           Forgot Your Password?
           <Link to="register">Click to Reset It</Link>
        </p>
      </div>
  )
}

Login = withFormik({
  mapPropsToValues: () => ({ username: undefined ,password: undefined}),

  // Custom sync validation
  validationSchema: Yup.object().shape({
    username: Yup.string()
      .required('username required'),
    password: Yup.string()
      .required('passworld required'),
  }),

  handleSubmit: async (values, { setSubmitting, props, setFieldError }) => {
    const {username, password} = values
    const auth = {
      username: username,
      password: password
    }
    const res = await API.get('/tokens',{auth})
    const {status, data} = res
    if (status === 200){
      setToken(data.token)
      store.loginAction()
      setSubmitting(false)
      const name = JSON.parse(atob(data.token.split('.')[1])).user_name
      toast.success(`🦄 Welcome ${name}`, {
        position: "top-center",
        autoClose: 5000,
        hideProgressBar: false,
        closeOnClick: true,
        pauseOnHover: true,
        draggable: true,
        progress: undefined,
        });
      if (!props.location.state) {
        props.history.push('/')
      } else {
        props.history.push(props.location.state.from.pathname)
      }
    } else {
      setFieldError("username", 'Invalid username or password.')
      setFieldError("password", 'Invalid username or password.')
    }
  }
})(Login);


export default Login
